/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _demo_include_h__
#define _demo_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-c11`
// (Use 6E543CF9-1C21-40CC-9367-A0707FCA87C8 instead of mulle-c11, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-c11 no-header`
//    rename              : `mulle-sde dependency|library set mulle-c11 include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-c11 <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-c11 [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-c11 [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-c11 [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-c11 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-c11/mulle-c11.h>   // mulle-c11

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove libbacktrace`
// (Use 7B3EB52B-6473-4202-A12E-8AD8940590DD instead of libbacktrace, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark libbacktrace no-header`
//    rename              : `mulle-sde dependency|library set libbacktrace include whatever.h`
//    reorder             : `mulle-sde dependency move libbacktrace <up|down>`
//    toggle #include: `mulle-sde dependency mark libbacktrace [no-]import`
//    toggle public       : `mulle-sde dependency mark libbacktrace [no-]public`
//    toggle optional     : `mulle-sde dependency mark libbacktrace [no-]require`
//    remove for platform : `mulle-sde dependency mark libbacktrace no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#ifdef __has_include
# if __has_include(<backtrace.h>)
#  include <backtrace.h>   // libbacktrace
#  define HAVE_LIB_LIBBACKTRACE
# endif
#endif

#endif
