/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _demo_include_private_h__
#define _demo_include_private_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-dlfcn`
// (Use 93126984-760F-4EF9-9824-A301B05FB48A instead of mulle-dlfcn, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-dlfcn no-header`
//    rename              : `mulle-sde dependency|library set mulle-dlfcn include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-dlfcn <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-dlfcn [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-dlfcn [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-dlfcn [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-dlfcn no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-dlfcn/mulle-dlfcn.h>   // mulle-dlfcn

#endif
