#ifndef demo_include_h__
#define demo_include_h__

#define HAVE_INCLUDE_DEMO

/* This is a central include file to keep dependencies out of the library
   C files. It is usally included by .h files only.

   The advantage is that now .c and .h files become motile. They can
   be moved to other projects and don't need to be edited. Also less typing...

   Therefore it is important that this file is called "include.h" and
   not "demo-include.h" to keep the #include statements in the
   library code uniform.

   The C-compiler will pick up the nearest one.
*/

/* Include the header file automatically generated by mulle-sourcetree-to-c.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#include "_demo-include.h"

#ifndef DEMO_GLOBAL
# ifdef DEMO_BUILD
#  define DEMO_GLOBAL    MULLE_C_GLOBAL
# else
#  if defined( DEMO_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( DEMO_INCLUDE_STATIC))
#   define DEMO_GLOBAL   MULLE_C_GLOBAL
#  else
#   define DEMO_GLOBAL   extern
#  endif
# endif
#endif

/* You can add some more include statements here */

#include "demo-version.h"

#endif
