#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/mulle-stacktrace.c
src/mulle-stacktrace-execinfo.c
)

set( STANDALONE_SOURCES
src/mulle-stacktrace-standalone.c
)
